### Option:Plugins.MSSQL.System.Path
#	Path to external plugin executable.
#
# Mandatory: yes
# Default:
# Plugins.MSSQL.System.Path=

### Option: Plugins.MSSQL.Timeout
#	Amount of time to wait for a server to respond when first connecting and on
#   follow up operations in the session.
#
# Mandatory: no
# Range: 1-30
# Default:
# Plugins.MSSQL.Timeout=<Global timeout>

### Option: Plugins.MSSQL.KeepAlive
#	Time in seconds for waiting before unused connections will be closed.
#
# Mandatory: no
# Range: 60-900
# Default:
# Plugins.MSSQL.KeepAlive=300

### Option: Plugins.MSSQL.Sessions.*.Uri
#	Uri to connect. "*" should be replaced with a session name.
#
# Mandatory: no
# Range:
#   Must matches the URI format.
#   The only supported schema is "tcp".
#   Embedded credentials will be ignored.
# Default:
# Plugins.MSSQL.Sessions.*.Uri=

### Option: Plugins.MSSQL.Sessions.*.User
#	Username to send to protected MSSQL server. "*" should be replaced with a session name.
#
# Mandatory: no
# Default:
# Plugins.MSSQL.Sessions.*.User=

### Option: Plugins.MSSQL.Sessions.*.Password
#	Password to send to protected MSSQL server. "*" should be replaced with a session name.
#
# Mandatory: no
# Default:
# Plugins.MSSQL.Sessions.*.Password=

### Option: Plugins.MSSQL.Default.Uri
#	Uri to connect. Default value used if no other is specified.
#
# Mandatory: no
# Range:
#   Must matches the URI format.
#   The only supported schema is "tcp".
#   Embedded credentials will be ignored.
# Default:
# Plugins.MSSQL.Default.Uri=

### Option: Plugins.MSSQL.Default.User
#	Username to send to protected MSSQL server. Default value used if no other is specified.
#
# Mandatory: no
# Default:
# Plugins.MSSQL.Default.User=

### Option: Plugins.MSSQL.Default.Password
#	Password to send to protected MSSQL server. Default value used if no other is specified.
#
# Mandatory: no
# Default:
# Plugins.MSSQL.Default.Password=
