version: "3.1"

services:
  mssql-plugin-tests:
    image: agent2-plugin/mssql-tests:7.0
    build:
      context: tests
      dockerfile: Dockerfile
    depends_on:
      mssql:
        condition: service_healthy
      mssql-plugin:
        condition: service_healthy

  # TODO: add custom queries
  mssql-plugin:
    image: agent2-plugin/mssql:7.0
    build:
      context: ..
      dockerfile: docker/mssql-plugin/Dockerfile
    environment:
      ZBX_PASSIVESERVERS: 127.0.0.1
    healthcheck:
      test: [ "CMD", "/usr/bin/zabbix_get", "-s", "127.0.0.1", "-p", "10050", "-k", "agent.ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # TODO: handle different versions of mssql
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      # mssql requires legit password
      MSSQL_SA_PASSWORD: haej7vaefa7Aicee
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "haej7vaefa7Aicee", "-Q", "select 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    # ports:
    #   - "1433:1433"

# docker run \
#  -e ZBX_DEBUGLEVEL=4 \
#  zabbix/zabbix-agent:ubuntu-trunk
#
# --name some-zabbix-agent
# -e ZBX_HOSTNAME="some-hostname"
# -e ZBX_SERVER_HOST="some-zabbix-server"
# --init -d zabbix/zabbix-agent:tag
#
#         zabbix/zabbix-agent:ubuntu-trunk
